if [ -d "$HOME/scripts/bin" ] ; then
    PATH="$PATH:$HOME/scripts/bin"
fi

. ~/.bash_aliases

export EDITOR="/usr/bin/vim"
export PAGER=less       # reader for MAN pages


[[ -s "$HOME/scripts/git-completion.bash" ]] && source "$HOME/scripts/git-completion.bash" 

