
# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    #eval "`dircolors -b`"
    alias ls='ls --color=auto -h'
    alias dir='ls --color=auto --format=vertical'
    alias vdir='ls --color=auto --format=long'
fi

#export PS1='[\u@\033[41m\h\$\033[0m \W]\$ '


# some more ls aliases
alias l='ls -hG'
alias ll='l -lrt'
alias la='l -A'
alias lla='ll -A'
alias df='df -h'
alias top='top -F -R -o cpu'
alias updatedb='sudo /usr/libexec/locate.updatedb'
alias d='du -sch'
alias vi=vim
alias gs='git status'
alias gf='git fetch --all'


alias grep='grep --color=auto' 
#alias mv='mv -i'
#alias cp='cp -i'
alias d='du -sh'
alias find-windows-line-endings="grep -IUrl $(printf '\r') ."

alias set-java8openjdk='export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk8u172-b11 && export PATH=$JAVA_HOME/bin:$PATH && java -version'
alias set-java8='export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home && export PATH=$JAVA_HOME/bin:$PATH && java -version'
alias set-java11='export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home && export PATH=$JAVA_HOME/bin:$PATH && java -version'
