CREATE USER 'USERNAME'@'localhost' IDENTIFIED BY 'PASSWORD';

GRANT USAGE ON * . * TO 'USERNAME'@'localhost' IDENTIFIED BY 'PASSWORD' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS `USERNAME` ;

GRANT ALL PRIVILEGES ON `USERNAME` . * TO 'USERNAME'@'localhost';
